package com.example.hectorvera.greendao.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.hectorvera.greendao.db.personalInformation;
import com.example.hectorvera.greendao.db.personalDirection;

import com.example.hectorvera.greendao.db.personalInformationDao;
import com.example.hectorvera.greendao.db.personalDirectionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig personalInformationDaoConfig;
    private final DaoConfig personalDirectionDaoConfig;

    private final personalInformationDao personalInformationDao;
    private final personalDirectionDao personalDirectionDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        personalInformationDaoConfig = daoConfigMap.get(personalInformationDao.class).clone();
        personalInformationDaoConfig.initIdentityScope(type);

        personalDirectionDaoConfig = daoConfigMap.get(personalDirectionDao.class).clone();
        personalDirectionDaoConfig.initIdentityScope(type);

        personalInformationDao = new personalInformationDao(personalInformationDaoConfig, this);
        personalDirectionDao = new personalDirectionDao(personalDirectionDaoConfig, this);

        registerDao(personalInformation.class, personalInformationDao);
        registerDao(personalDirection.class, personalDirectionDao);
    }
    
    public void clear() {
        personalInformationDaoConfig.getIdentityScope().clear();
        personalDirectionDaoConfig.getIdentityScope().clear();
    }

    public personalInformationDao getPersonalInformationDao() {
        return personalInformationDao;
    }

    public personalDirectionDao getPersonalDirectionDao() {
        return personalDirectionDao;
    }

}
