package com.example.hectorvera.greendao.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PERSONAL_DIRECTION".
 */
public class personalDirection {

    private Long Pd_id;
    private String Street;
    private String Zip_Code;
    private String State;

    public personalDirection() {
    }

    public personalDirection(Long Pd_id) {
        this.Pd_id = Pd_id;
    }

    public personalDirection(Long Pd_id, String Street, String Zip_Code, String State) {
        this.Pd_id = Pd_id;
        this.Street = Street;
        this.Zip_Code = Zip_Code;
        this.State = State;
    }

    public Long getPd_id() {
        return Pd_id;
    }

    public void setPd_id(Long Pd_id) {
        this.Pd_id = Pd_id;
    }

    public String getStreet() {
        return Street;
    }

    public void setStreet(String Street) {
        this.Street = Street;
    }

    public String getZip_Code() {
        return Zip_Code;
    }

    public void setZip_Code(String Zip_Code) {
        this.Zip_Code = Zip_Code;
    }

    public String getState() {
        return State;
    }

    public void setState(String State) {
        this.State = State;
    }

}
